### ISSUE TITLE
No JSON object error when running TASS.py

### ISSUE THREAD

**Issue by WesleyEe** [TechBubbleTechnologies/IoT-JumpWay-RPI-Examples#2]
It seems that while following the steps written in this post, I have encountered a problem I cannot solve regarding json. 

After I have taken my own pictures and placed them in the training folder, and change self.train=0 to self.train=1, I get this error when trying to run TASS.py

File "usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
raise ValueError ("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Does anyone know what is causing this, and how to solve it?

**Comment by AdamMiltonBarker** [comment]
Hi sorry for the delayed reply, can you confirm that your config.json file:
 
https://github.com/TechBubbleTechnologies/IoT-JumpWay-RPI-Examples/blob/master/Computer-Vision/Python/config.json

is present and after you have made your changes to the file, pass it through a json validator to confirm that it is valid json. 

If you can confirm the above I will have some time this week to reinstall the project and test.

**Comment by thewesleyee** [comment]
It turns out that my JSON is not valid, and hence may be causing the No JSON object found error.

This was the result I received:
Error: Parse error on line 12:
...		"SystemLocation": Living Room,		"Syst
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

Seems that I need to have a number instead of Living Room under SystemLocation

**Comment by WesleyEe** [comment]
It turns out that my JSON is not valid, and hence may be causing the No JSON object found error.

This was the result I received:
Error: Parse error on line 12:
...	"SystemLocation": Living Room,	"Syst
-----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

Seems that I need to have a number instead of Living Room under SystemLocation

**Comment by AdamMiltonBarker** [comment]
The system location should be your location ID from the jumpway. The docs explain these settings. If there any additional information you need feel free to let me know. Just double check that everything is the same as the demo code and your settings are correct. Will leave this ticket open waiting for your response.

**Comment by AdamMiltonBarker** [comment]
Hi buddy how did you get on, if the issues resolved please close the ticket, feel free to ask any questions.

**Comment by WesleyEe** [comment]
Hi thanks so much for the replies! Yes I have the issue resolved, seems that I got a little lost with multiple locations and ids etc.

Thank you :)

**Comment by AdamMiltonBarker** [comment]
No problem glad you worked it out.
