### ISSUE TITLE
Installation Error after step 11 because of  libgtk2.0-dev 

### ISSUE THREAD

**Issue by apondu** [TechBubbleTechnologies/IoT-JumpWay-RPI-Examples#3]
Hi,

Thanks for the clean and clear step by step process of installing OpenCV its very easy for a newbie like me who is trying to learn

I just wanted to update you that after step 11 of cmake i was always getting error so i was googling around and found we need to update

apt-get install libgtk2.0-dev pkg-config

Because we had already install libgtk2.0-dev in step 3 but still it was not working after i executed the statement mentioned above and then the statement of cmake as in step 11 it went thru fine and configuration was done.

I just wanted to update may be it will be helpful for someone.

Again thanks for the stet by step process.

**Comment by AdamMiltonBarker** [comment]
Thanks for the feedback, I will add it as a note and leave this issue open until added.

**Comment by AdamMiltonBarker** [comment]
Thanks the suggestion has been added to the docs. Thanks for pointing it out.

https://github.com/TechBubbleTechnologies/IoT-JumpWay-RPI-Examples/blob/master/_DOCS/2-Installing-OpenCV.md
