### ISSUE TITLE
No developer data

### ISSUE THREAD

**Issue by Kevlar316** [TechBubbleTechnologies/IoT-JumpWay-RPI-Examples#6]
Hey, I have completed this now and it looks as though it is all connected on the Raspberry Pi but I can't see any control data on the developer dashboard. Let me know if you need any more details.

**Comment by AdamMiltonBarker** [comment]
All services are running correctly, are you sure you connected up the details right in config ? Can we close other ticket off or are you still have issues related to that ticket mate ?

**Comment by Kevlar316** [comment]
I have commented on teh other ticket to close. I have checked the usernames and passwords from the config file. I will double check again and let you know.

**Comment by Kevlar316** [comment]
Hello, I  have been in and checked and checked again and the device and application details and passwords match the IoT Developer dashboard. I am thinking there is something else I've missed but I cant see what it is. 
Thanks :-)

**Comment by AdamMiltonBarker** [comment]
Hi how are you? If your connection name is a type of food, you are connecting to a channel you do not have authorization to, your connections are going to:

```
0/Applications/0/Status
0/Devices/0/0/Commands
```

Which is not correct, this suggests that your config file is incorrect, but could also be a bug on our side let me check it and get back to you.

**Comment by AdamMiltonBarker** [comment]
Can you remind me which example you are using at the moment please.

**Comment by Kevlar316** [comment]
I am in the Raspberry Pi Basic LED Python example. It is a type of food ;-)

**Comment by Kevlar316** [comment]
I have also done a fresh clone and compared the config files and they look the same, other than my credentials

**Comment by AdamMiltonBarker** [comment]
Ok thanks I will check the source code now, that is the issue though the application is publishing against a topic it does not have authorization to. Let me check the code as soon as I can and I will get back to you buddy.

**Comment by Kevlar316** [comment]
Awesome, thanks mate, no rush

**Comment by AdamMiltonBarker** [comment]
Everything looks correct mate, can you follow these steps.

1. Stop any program that is attempting to connect to the IoT JumpWay.
2. Try connecting only the device program, I will check to see that that is connecting first.
3. Print out the contents of self.configs for both the application and device programs and paste them here, please cover you passwords completely and your usernames / device & application names, but make sure they are correct. 

Cheers will keep an eye out now for you connecting  on the device.

**Comment by AdamMiltonBarker** [comment]
It also looks like you are attempting to connect multiple times whilst already connected the code does not do this so not sure how you are doing that, but lets debug the above first.

**Comment by AdamMiltonBarker** [comment]
Can you also paste the output of both your device and application program please.

**Comment by AdamMiltonBarker** [comment]
I have tested and this must be an error in your configs, please ensure the areas that says 0 are replaced with your IDs from the IoT JumpWay mate.

```

	"IoTJumpWaySettings": {
        "SystemLocation": 0,
        "SystemZone": 0,
        "SystemDeviceID": 0,
        "SystemDeviceName" : "Your Device Name",
        "SystemApplicationID": 0,
        "SystemApplicationName" : "Your Application Name"
    },
	"Sensors": {},
	"Actuators": {
        "LED": {
            "ID": 0,
            "PIN": 5
        }
    },
```

**Comment by AdamMiltonBarker** [comment]
I have tested and this must be an error in your configs, please ensure the areas that say 0 are replaced with your IDs from the IoT JumpWay mate, and "Your Device Name" and  "Your Application Name" are updated to the correct values, and obviously your actual connection details. At the moment you are connecting to:

```
0/Applications/0/Status
0/Devices/0/0/Commands
```

Which suggests that the configs are not updated correctly.

```

	"IoTJumpWaySettings": {
        "SystemLocation": 0,
        "SystemZone": 0,
        "SystemDeviceID": 0,
        "SystemDeviceName" : "Your Device Name",
        "SystemApplicationID": 0,
        "SystemApplicationName" : "Your Application Name"
    },
	"Sensors": {},
	"Actuators": {
        "LED": {
            "ID": 0,
            "PIN": 5
        }
    },
```

Just a reminder for this to work both the device and application programs need to be running.

**Comment by AdamMiltonBarker** [comment]
You can follow this part of the documentation to resolve your error, let me know if you need any further assistance, when you are happy you can close the issue mate.

https://github.com/TechBubbleTechnologies/IoT-JumpWay-RPI-Examples/tree/master/Basic-LED/Python#device--application-connection-credentials--sensor-settings

**Comment by Kevlar316** [comment]
Awesome, I have now got data showing up for my device on the dashboard. That's stage one complete now, bring on the next challenge!
Thanks for your help :-)

**Comment by AdamMiltonBarker** [comment]
No worries mate, glad you got it sorted ;)
